// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShuttleService.Data;

namespace ShuttleService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201001073630_sdb_10012020")]
    partial class sdb_10012020
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ShuttleService.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ShuttleService.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int>("DepartmentId");

                    b.Property<int?>("DepartmentListId");

                    b.Property<string>("DisplayName")
                        .HasColumnType("VARCHAR(80)");

                    b.Property<string>("Domain")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<int>("EmployeeId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentListId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ShuttleService.Models.ChargingCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired();

                    b.Property<DateTime>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ChargingCompanys");
                });

            modelBuilder.Entity("ShuttleService.Models.ChargingDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChargingCompanyId");

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<DateTime>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ChargingDepartments");
                });

            modelBuilder.Entity("ShuttleService.Models.CompanyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired();

                    b.Property<DateTime>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CompanyLists");
                });

            modelBuilder.Entity("ShuttleService.Models.DefaultApprover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApproverEmployeeId");

                    b.Property<string>("ApproverEmployeeNo")
                        .IsRequired();

                    b.Property<int?>("EmployeeId");

                    b.Property<string>("EmployeeNo")
                        .IsRequired();

                    b.Property<DateTime?>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.HasKey("Id");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DefaultApprovers");
                });

            modelBuilder.Entity("ShuttleService.Models.DepartmentList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyListId");

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<DateTime>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DepartmentLists");
                });

            modelBuilder.Entity("ShuttleService.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("CivilStatus")
                        .IsRequired();

                    b.Property<DateTime>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<DateTime>("License_Expiry");

                    b.Property<string>("License_Restriction")
                        .IsRequired();

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.Property<DateTime>("ModifyDate");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("ShuttleService.Models.DriverPassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDatetime");

                    b.Property<string>("CancelReason");

                    b.Property<string>("CancelledBy");

                    b.Property<DateTime?>("CancelledDatetime");

                    b.Property<int>("ChargingCompanyId");

                    b.Property<int>("ChargingDepartmentId");

                    b.Property<int>("CompanyListId");

                    b.Property<string>("CompanyOther");

                    b.Property<string>("ContactNo");

                    b.Property<string>("DeclinedBy");

                    b.Property<DateTime?>("DeclinedDatetime");

                    b.Property<string>("DeclinedReason");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<string>("DriverPassengerHeaderId");

                    b.Property<int?>("DriverPassengerHeaderId1");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("EmployeeNo");

                    b.Property<DateTime?>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("InitialApproverEmployeeNo");

                    b.Property<string>("Instructions")
                        .IsRequired();

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.Property<string>("Nationality")
                        .IsRequired();

                    b.Property<string>("Origin")
                        .IsRequired();

                    b.Property<string>("OriginalApproverEmployeeNo");

                    b.Property<int>("PassengerTypeId");

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("RemovedBy");

                    b.Property<DateTime?>("RemovedDatetime");

                    b.Property<string>("RemovedRemarks");

                    b.Property<string>("ReservedBy");

                    b.Property<DateTime?>("ReservedDatetime");

                    b.Property<int>("SMSRevision");

                    b.Property<DateTime?>("ServiceDate");

                    b.Property<long>("ServiceDateTimeStamp");

                    b.Property<int>("ServiceTypeId");

                    b.Property<int>("ShuttleId");

                    b.Property<string>("SmsId");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("SubmitDate");

                    b.Property<string>("TransactionId");

                    b.Property<string>("TripTimeFrom")
                        .IsRequired();

                    b.Property<string>("TripTimeTo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ChargingCompanyId");

                    b.HasIndex("ChargingDepartmentId");

                    b.HasIndex("CompanyListId");

                    b.HasIndex("DriverPassengerHeaderId1");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PassengerTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("DriverPassengers");
                });

            modelBuilder.Entity("ShuttleService.Models.DriverPassengerHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDatetime");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<int>("EmployeeId");

                    b.Property<DateTime?>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("InitialApproverEmployeeNo");

                    b.Property<string>("Instructions")
                        .IsRequired();

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Origin")
                        .IsRequired();

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<DateTime?>("ServiceDate");

                    b.Property<long>("ServiceDateTimeStamp");

                    b.Property<int>("ServiceTypeId");

                    b.Property<int>("ShuttleId");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("SubmitDate");

                    b.Property<string>("TempTransactionId");

                    b.Property<string>("TransactionId");

                    b.Property<string>("TripTimeFrom")
                        .IsRequired();

                    b.Property<string>("TripTimeTo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("DriverPassengerHeaders");
                });

            modelBuilder.Entity("ShuttleService.Models.EmailRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Group");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("ShuttleService.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlternateImmediateHead");

                    b.Property<DateTime?>("AlternateImmediateHeadValidFrom");

                    b.Property<DateTime?>("AlternateImmediateHeadValidTo");

                    b.Property<bool>("AlternateImmediateHeadValidity");

                    b.Property<string>("AlternativeEmail")
                        .IsRequired();

                    b.Property<int>("ChargingCompanyId");

                    b.Property<int>("ChargingDepartmentId");

                    b.Property<string>("CompanyEmail")
                        .IsRequired();

                    b.Property<int>("CompanyListId");

                    b.Property<int>("DepartmentListId");

                    b.Property<string>("EmployeeNo")
                        .IsRequired();

                    b.Property<DateTime>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<bool>("IsImmediateHead");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("LocalNumber")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.Property<DateTime>("ModifyDate");

                    b.Property<int>("NationalityId");

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("SupervisorEmployeeNo")
                        .IsRequired();

                    b.Property<int>("is_recomputed");

                    b.HasKey("Id");

                    b.HasIndex("CompanyListId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ShuttleService.Models.LockedEmployeeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<string>("LockedControlNo");

                    b.Property<DateTime?>("LockedFrom");

                    b.Property<string>("LockedRemarks");

                    b.Property<DateTime?>("LockedTo");

                    b.Property<string>("Process");

                    b.Property<string>("ProcessedBy");

                    b.Property<DateTime>("ProcessedDate");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LockedEmployeeLogs");
                });

            modelBuilder.Entity("ShuttleService.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Process");

                    b.Property<string>("ProcessedBy");

                    b.Property<DateTime>("ProcessedDate");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ShuttleService.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaintenanceControlNo");

                    b.Property<DateTime?>("MaintenanceFrom");

                    b.Property<string>("MaintenanceRemarks");

                    b.Property<DateTime?>("MaintenanceTo");

                    b.Property<string>("Process");

                    b.Property<string>("ProcessedBy");

                    b.Property<DateTime>("ProcessedDate");

                    b.Property<int>("VehicleListId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleListId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("ShuttleService.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NationalityName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("ShuttleService.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Value");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ShuttleService.Models.PassengerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PassengerTypes");
                });

            modelBuilder.Entity("ShuttleService.Models.ReservationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ReservationType");
                });

            modelBuilder.Entity("ShuttleService.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("ShuttleService.Models.Shuttle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssemblyArea");

                    b.Property<int>("DriverId");

                    b.Property<DateTime>("ServiceDate");

                    b.Property<long>("ServiceDateTimeStamp");

                    b.Property<int>("VehicleListId");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleListId");

                    b.ToTable("Shuttles");
                });

            modelBuilder.Entity("ShuttleService.Models.ShuttlePassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AmSnack");

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime?>("ApprovedDatetime");

                    b.Property<bool>("Breakfast");

                    b.Property<string>("CancelReason");

                    b.Property<string>("CancelledBy");

                    b.Property<DateTime?>("CancelledDatetime");

                    b.Property<int>("ChargingCompanyId");

                    b.Property<int>("ChargingDepartmentId");

                    b.Property<int>("CompanyListId");

                    b.Property<string>("CompanyOther");

                    b.Property<string>("ContactNo");

                    b.Property<string>("DeclinedBy");

                    b.Property<DateTime?>("DeclinedDatetime");

                    b.Property<string>("DeclinedReason");

                    b.Property<bool>("Dinner");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("EmployeeNo");

                    b.Property<DateTime?>("EncodeDate");

                    b.Property<string>("EncodedBy");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("InitialApproverEmployeeNo");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<DateTime?>("LodgingFrom");

                    b.Property<DateTime?>("LodgingTo");

                    b.Property<bool>("Lunch");

                    b.Property<string>("MiddleName");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<string>("Name");

                    b.Property<string>("Nationality")
                        .IsRequired();

                    b.Property<string>("OriginalApproverEmployeeNo");

                    b.Property<int>("PassengerTypeId");

                    b.Property<bool>("PmSnack");

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("RemovedBy");

                    b.Property<DateTime?>("RemovedDatetime");

                    b.Property<string>("RemovedRemarks");

                    b.Property<string>("ReservedBy");

                    b.Property<DateTime?>("ReservedDatetime");

                    b.Property<int>("SMSRevision");

                    b.Property<DateTime?>("ServiceDate");

                    b.Property<long>("ServiceDateTimeStamp");

                    b.Property<int>("ShuttleId");

                    b.Property<string>("SmsId");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("SubmitDate");

                    b.Property<string>("TransactionId");

                    b.Property<string>("TripTime");

                    b.Property<int>("TripTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ChargingCompanyId");

                    b.HasIndex("ChargingDepartmentId");

                    b.HasIndex("CompanyListId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PassengerTypeId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("ShuttlePassengers");
                });

            modelBuilder.Entity("ShuttleService.Models.ShuttlePassengerStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusDescription")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ShuttlePassengerStatuses");
                });

            modelBuilder.Entity("ShuttleService.Models.SMSLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Process");

                    b.Property<string>("ProcessedBy");

                    b.Property<DateTime?>("ProcessedDate");

                    b.Property<long>("ServiceDateTimeStamp");

                    b.Property<int>("Status");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("SMSLogs");
                });

            modelBuilder.Entity("ShuttleService.Models.SmsTransactionCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApproverEmployeeNo");

                    b.Property<string>("OriginalApproverEmployeeNo");

                    b.Property<string>("ReferenceNo");

                    b.Property<string>("Remarks");

                    b.Property<int>("ReservationTypeId");

                    b.Property<int>("Status");

                    b.Property<string>("TransactionId");

                    b.HasKey("Id");

                    b.ToTable("SmsTransactionCodes");
                });

            modelBuilder.Entity("ShuttleService.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CancelReason");

                    b.Property<string>("CancelledBy");

                    b.Property<DateTime?>("CancelledDatetime");

                    b.Property<int>("Capacity");

                    b.Property<int>("DriverId");

                    b.Property<string>("EmailBy");

                    b.Property<DateTime?>("EmailDatetime");

                    b.Property<int>("EmailStatus");

                    b.Property<int>("EmailVersion");

                    b.Property<DateTime?>("EncodeDate");

                    b.Property<string>("EncodedBy")
                        .IsRequired();

                    b.Property<string>("LastModifiedBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int>("RemainingCapacity");

                    b.Property<int>("RemainingCapacityPM");

                    b.Property<string>("Remarks")
                        .HasColumnType("VARCHAR(250)");

                    b.Property<int>("ReservationTypeId");

                    b.Property<string>("SMSBy");

                    b.Property<DateTime?>("SMSDatetime");

                    b.Property<int>("SMSStatus");

                    b.Property<int>("SMSVersion");

                    b.Property<long>("ServiceDateTimeStamp");

                    b.Property<DateTime>("ServiceEndDate");

                    b.Property<DateTime>("ServiceStartDate");

                    b.Property<int>("Status");

                    b.Property<string>("TripControlNo");

                    b.Property<int>("VehicleListId");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ReservationTypeId");

                    b.HasIndex("VehicleListId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("ShuttleService.Models.TripType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TripTypes");
                });

            modelBuilder.Entity("ShuttleService.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<DateTime>("CodingDay");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("PlateNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ShuttleService.Models.VehicleList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<int>("CodingDay");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("PlateNumber")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("VehicleLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ShuttleService.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShuttleService.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShuttleService.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ShuttleService.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShuttleService.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.ApplicationUser", b =>
                {
                    b.HasOne("ShuttleService.Models.DepartmentList", "DepartmentList")
                        .WithMany()
                        .HasForeignKey("DepartmentListId");

                    b.HasOne("ShuttleService.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.DefaultApprover", b =>
                {
                    b.HasOne("ShuttleService.Models.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId");

                    b.HasOne("ShuttleService.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("ShuttleService.Models.DriverPassenger", b =>
                {
                    b.HasOne("ShuttleService.Models.ChargingCompany", "ChargingCompany")
                        .WithMany()
                        .HasForeignKey("ChargingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.ChargingDepartment", "ChargingDepartment")
                        .WithMany()
                        .HasForeignKey("ChargingDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.CompanyList", "CompanyList")
                        .WithMany()
                        .HasForeignKey("CompanyListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.DriverPassengerHeader", "DriverPassengerHeader")
                        .WithMany("DriverPassengers")
                        .HasForeignKey("DriverPassengerHeaderId1");

                    b.HasOne("ShuttleService.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.PassengerType", "PassengerType")
                        .WithMany()
                        .HasForeignKey("PassengerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.DriverPassengerHeader", b =>
                {
                    b.HasOne("ShuttleService.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.Employee", b =>
                {
                    b.HasOne("ShuttleService.Models.CompanyList", "CompanyList")
                        .WithMany()
                        .HasForeignKey("CompanyListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.LockedEmployeeLog", b =>
                {
                    b.HasOne("ShuttleService.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.MaintenanceLog", b =>
                {
                    b.HasOne("ShuttleService.Models.VehicleList", "VehicleList")
                        .WithMany()
                        .HasForeignKey("VehicleListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.Shuttle", b =>
                {
                    b.HasOne("ShuttleService.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.VehicleList", "VehicleList")
                        .WithMany()
                        .HasForeignKey("VehicleListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.ShuttlePassenger", b =>
                {
                    b.HasOne("ShuttleService.Models.ChargingCompany", "ChargingCompany")
                        .WithMany()
                        .HasForeignKey("ChargingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.ChargingDepartment", "ChargingDepartment")
                        .WithMany()
                        .HasForeignKey("ChargingDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.CompanyList", "CompanyList")
                        .WithMany()
                        .HasForeignKey("CompanyListId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.PassengerType", "PassengerType")
                        .WithMany()
                        .HasForeignKey("PassengerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.TripType", "TripType")
                        .WithMany()
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShuttleService.Models.Trip", b =>
                {
                    b.HasOne("ShuttleService.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.ReservationType", "ReservationType")
                        .WithMany()
                        .HasForeignKey("ReservationTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShuttleService.Models.VehicleList", "VehicleList")
                        .WithMany()
                        .HasForeignKey("VehicleListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
